import { BTN, INTRO_TICKS } from '../../../src/core';
import type { Session } from '../../../src/game/session';
import { ROUND_OVER_FRAMES, SCOREBOARD_FRAMES, SKIP_AFTER } from '../../../src/game/session';
import { stageScreen, START_DELAY_FRAMES } from '../../../src/screens/stage';
import { mkApp, press, idle } from './helpers';

describe('fase e batalha', () => {
  it('ESQ/DIR trocam a fase com volta', () => {
    const { app } = mkApp();
    app.go(stageScreen(app));
    press(app, BTN.LEFT);
    expect(app.settings.setup.stage).toBe(10);
    press(app, BTN.RIGHT); press(app, BTN.RIGHT);
    expect(app.settings.setup.stage).toBe(2);
  });
  it('A mostra BATALHA! e depois abre a partida com a formação escolhida', () => {
    const { app } = mkApp();
    app.settings.setup.slots = ['human', 'cpu', 'off', 'human', 'off'];
    app.settings.setup.stage = 3;
    app.settings.names[0] = 'ANA';
    const scr = stageScreen(app);
    app.go(scr);
    press(app, BTN.A);
    expect(scr.starting).toBe(START_DELAY_FRAMES - 1);
    idle(app, START_DELAY_FRAMES);
    expect(app.screen.id).toBe('battle');
    const s = (app.screen as unknown as { session: Session }).session;
    expect(s.cfg.stage).toBe(3);
    expect(s.cfg.humans).toEqual([true, false, false, true, false]);
    expect(s.cfg.rules.active).toEqual([true, true, false, true, false]);
    expect(s.cfg.names[0]).toBe('ANA');
  });
  it('sair pela pausa pede confirmação; volta para a seleção de fase só depois de A; a animação congela na pausa', () => {
    const { app } = mkApp();
    const scr = stageScreen(app);
    app.go(scr);
    press(app, BTN.A);
    idle(app, START_DELAY_FRAMES);
    expect(app.screen.id).toBe('battle');
    press(app, BTN.START, 0);
    const f = app.frame;
    idle(app, 10);
    expect(app.frame).toBe(f);
    press(app, BTN.B, 0);
    expect(app.screen.id).toBe('battle');
    const s = (app.screen as unknown as { session: Session }).session;
    expect(s.confirmQuit).toBe(true);
    press(app, BTN.A, 0);
    expect(app.screen.id).toBe('stage');
  });
  it('formação toda CPU: pausa e confirma a saída com um dispositivo sem jogador atribuído', () => {
    const { app } = mkApp();
    app.settings.setup.slots = ['cpu', 'cpu', 'off', 'off', 'off'];
    const scr = stageScreen(app);
    app.go(scr);
    press(app, BTN.A);
    idle(app, START_DELAY_FRAMES);
    expect(app.screen.id).toBe('battle');
    const s = (app.screen as unknown as { session: Session }).session;
    expect(s.anyControl).toBe(true);
    press(app, BTN.START);
    const f = app.frame;
    idle(app, 5);
    expect(app.frame).toBe(f);
    expect(s.paused).toBe(true);
    press(app, BTN.B);
    expect(s.confirmQuit).toBe(true);
    press(app, BTN.A);
    expect(app.screen.id).toBe('stage');
  });
  it('formação com humanos: partida vai à vitória e volta para a fase depois de START', () => {
    const { app } = mkApp();
    app.settings.setup.slots = ['human', 'human', 'off', 'off', 'off'];
    app.settings.setup.rules.matches = 1;
    app.go(stageScreen(app));
    press(app, BTN.A);
    idle(app, START_DELAY_FRAMES);
    expect(app.screen.id).toBe('battle');
    const s = (app.screen as unknown as { session: Session }).session;
    idle(app, INTRO_TICKS);
    s.round.players.forEach((p, i) => { if (i !== 0) p.state = 'out'; });
    idle(app, 140);
    expect(s.phase).toBe('roundOver');
    idle(app, ROUND_OVER_FRAMES);
    expect(s.phase).toBe('scoreboard');
    idle(app, SCOREBOARD_FRAMES);
    expect(s.phase).toBe('victory');
    idle(app, SKIP_AFTER + 1);
    press(app, BTN.START, 0);
    expect(app.screen.id).toBe('stage');
  });
  it('formação inválida na fase: A/START voltam para jogadores em vez de começar', () => {
    const { app } = mkApp();
    app.settings.setup.slots = ['human', 'off', 'off', 'off', 'off'];
    app.go(stageScreen(app));
    press(app, BTN.A);
    expect(app.screen.id).toBe('players');
  });
});
