import type { ExtraGlyph } from '../types';
// Glifos próprios do estilo banner (16 px, mesmos índices das letras da ROM — `o` = 3 contorno/traço branco, `#` = 1
// corpo verde-escuro e faixa escura em volta, `+` = 2 brilho verde). D, O, G e B não existem em PAUSE!/HURRY!/TIME
// UP!; foram desenhados à mão no traço das letras da ROM vizinhas: contorno branco de 1 px por fora, "miolo" branco
// maciço no lugar do furo (como o furo do P), brilho verde no lado esquerdo de dentro, faixa escura de 1 px em volta e
// a sombra escura embaixo (linha 15), com a mesma altura (linhas 1-15) e largura parecida com P/U (13-14 px de tinta).
// Largura 16 com `spacing` −4 = avanço 12, igual ao das letras cortadas (10-13).
// Á reaproveita o A recortado da ROM (`base: 'A'`) e só acrescenta o acento agudo à direita do bico do A (linhas 0-1),
// que é onde sobra espaço sem encolher a letra.
const L = { o: 3, '#': 1, '+': 2 } as const;

export const EXTRA: readonly ExtraGlyph[] = [
  { ch: 'O', legend: L, rows: [
    '................',
    '.....oooooo.....',
    '....o+######o#..',
    '...o#########o#.',
    '..o+###+o+###o#.',
    '..o###+ooo+##o#.',
    '.o+###+ooo+##o#.',
    '.o####+ooo+##o#.',
    '.o####+ooo###o#.',
    '.o+###+ooo##o#..',
    '.#o###+oo+##o#..',
    '.#o+###o+###o#..',
    '..#o+######o#...',
    '...#o+####o#....',
    '....#ooooo#.....',
    '.....#####......',
  ] },
  { ch: 'D', legend: L, rows: [
    '................',
    '..oooooooo......',
    '..o+######o#....',
    '..o########o#...',
    '..o+##+o+###o#..',
    '..o###ooo+###o#.',
    '..o+##ooo+###o#.',
    '..o###ooo+###o#.',
    '..o###ooo####o#.',
    '..o+##ooo###o#..',
    '..o###oo+###o#..',
    '..o+##o+###o#...',
    '..o+#######o#...',
    '..o+######o#....',
    '..#ooooooo#.....',
    '...#######......',
  ] },
  { ch: 'G', legend: L, rows: [
    '................',
    '.....oooooo.....',
    '....o+######o#..',
    '...o#########o#.',
    '..o+###+oooooo#.',
    '..o###+o#.......',
    '.o+###+o#.......',
    '.o####+o#oooo...',
    '.o####+o+####o#.',
    '.o+###+ooo+##o#.',
    '.#o###+oo+##o#..',
    '.#o+###o+###o#..',
    '..#o+######o#...',
    '...#o+####o#....',
    '....#ooooo#.....',
    '.....#####......',
  ] },
  { ch: 'B', legend: L, rows: [
    '................',
    '..ooooooooo.....',
    '..o+#######o#...',
    '..o+##oo+###o#..',
    '..o###oo+###o#..',
    '..o+##o+###o#...',
    '..o+#######o#...',
    '..o########+o#..',
    '..o+##ooo+###o#.',
    '..o###ooo+###o#.',
    '..o###ooo####o#.',
    '..o+##oo+###o#..',
    '..o+########o#..',
    '..o+#######o#...',
    '..#oooooooo#....',
    '...########.....',
  ] },
  { ch: 'Á', base: 'A', legend: L, rows: [
    '............oo',
    '..........oo#.',
    ...Array.from({ length: 14 }, () => '..............'),
  ] },
];
