import type { ExtraGlyph } from '../types';
/** Glifos próprios no estilo da tela-título (bloco geométrico simples: contorno 1, preenchimento f — os mesmos
 * índices "ciano" usados por NORMAL GAME/BATTLE GAME/PASSWORD, para as letras novas ficarem na mesma cor das
 * recortadas da ROM numa frase PT-BR). J, Ç, U, H e !: nenhuma das 3 frases cianas tem essas letras (U e H e !
 * só aparecem em PUSH START BUTTON!, que usa a família de índices "amarela" — ver maps/titleMenu.ts). Õ: O
 * recortado da ROM (`base: 'O'`, sem pixels dele aqui) + til próprio por cima. */
export const EXTRA: readonly ExtraGlyph[] = [
  { ch: 'Ç', rows: [
    '.1ffffffff..',
    '11ffffffff..',
    'ff11111111..',
    'ff1.........',
    'ff1.........',
    'ff1.........',
    'ff1.........',
    'ff1.........',
    'ff1.........',
    'ff1.........',
    'ff1.........',
    'ff11111111..',
    '11ffffffff..',
    '.1ffffffff..',
    '....1f......',
    '.....1f.....',
  ] },
  { ch: 'J', rows: [
    '............',
    '...1ffffff..',
    '...1ffffff..',
    '...111ff11..',
    '.....1ff1...',
    '.....1ff1...',
    '.....1ff1...',
    '.....1ff1...',
    '111..1ff1...',
    'ff1..1ff1...',
    'ff1..1ff1...',
    'ff1..1ff1...',
    'ff1111ff1...',
    '11ffff111...',
    '.1ffff1.....',
    '............',
  ] },
  { ch: 'H', rows: [
    '............',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff111111ff..',
    'ffffffffff..',
    'ffffffffff..',
    'ff111111ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    '............',
  ] },
  { ch: 'U', rows: [
    '............',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff1....1ff..',
    'ff111111ff..',
    '11ffffff11..',
    '.1ffffff1...',
    '............',
  ] },
  { ch: '!', rows: [
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1ff1.......',
    '.1111.......',
    '............',
    '.1ff1.......',
    '.1ff1.......',
    '.1111.......',
    '............',
    '............',
  ] },
  { ch: 'Õ', rows: [
    '............',
    '..ff..ff....',
    'ff..ff......',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
  ], base: 'O' },
];
